# Generated by Django 5.1.6 on 2025-08-14 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blog", "0003_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComicPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_number", models.PositiveIntegerField(unique=True)),
                ("title", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="comics/pages/")),
                ("description", models.TextField(blank=True)),
                ("transcript", models.JSONField(blank=True, default=dict)),
                ("is_nsfw", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["page_number"],
                "indexes": [
                    models.Index(
                        fields=["page_number"], name="comics_comi_page_nu_bb4095_idx"
                    ),
                    models.Index(
                        fields=["is_nsfw", "published_at"],
                        name="comics_comi_is_nsfw_4fd38d_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ComicComment",
            fields=[
                (
                    "comment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="blog.comment",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="comics.comicpage",
                    ),
                ),
            ],
            bases=("blog.comment",),
        ),
    ]
