# Generated by Django 5.1.6 on 2025-08-14 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_comment"),
        ("comics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comicpage",
            name="blog_post",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comic_page",
                to="blog.blogpost",
            ),
        ),
        migrations.DeleteModel(
            name="ComicComment",
        ),
    ]
