# Generated by Django 5.1.6 on 2025-08-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comics", "0002_comicpage_blog_post_delete_comiccomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comicpage",
            name="description_html",
            field=models.TextField(blank=True),
        ),
    ]
