# Generated by Django 5.2.10 on 2026-01-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('path', models.SlugField(help_text="URL path for this page (e.g., 'my-page' will be accessible at /my-page)", max_length=200, unique=True)),
                ('content', models.TextField(help_text='Markdown content for the page')),
                ('content_html', models.TextField(blank=True, editable=False)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='custompages/previews/')),
                ('sidebar_links', models.JSONField(blank=True, default=list, help_text='JSON array of sidebar links. Format: [{"label": "Link Name", "url": "/path"}, ...]')),
                ('meta_description', models.TextField(blank=True)),
                ('meta_title', models.CharField(blank=True, help_text='Override page title for SEO', max_length=200)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['path', 'is_published'], name='custompages_path_c4193a_idx'), models.Index(fields=['is_published'], name='custompages_is_publ_6eec9f_idx')],
            },
        ),
    ]
