# Generated by Django 5.2.11 on 2026-05-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custompages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="custompage",
            name="path",
            field=models.SlugField(
                help_text="URL path for this page (e.g., 'my-page' will be accessible at /cust/my-page)",
                max_length=200,
                unique=True,
            ),
        ),
    ]
