# Generated by Django 5.2.11 on 2026-08-06 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RumbleSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Master switch. When off, public pages show 'come back next year!'.",
                    ),
                ),
                (
                    "signups_open",
                    models.BooleanField(
                        default=False,
                        help_text="Allow new contestants to enter at /voreday/enter.",
                    ),
                ),
                (
                    "advance_to_next_match",
                    models.BooleanField(
                        default=False,
                        help_text="Check and save to close the current voting match and open the next one. Clears itself after save.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rumble Settings",
                "verbose_name_plural": "Rumble Settings",
            },
        ),
        migrations.CreateModel(
            name="Contestant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Name shown on the bracket (not necessarily username).",
                        max_length=100,
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="vore_day_rumble/pfps/"
                    ),
                ),
                (
                    "bracket_position",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Slot in the current shuffle. Reassigned whenever someone signs up.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vore_day_rumble_entry",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["bracket_position", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_number", models.PositiveIntegerField(default=1)),
                (
                    "position",
                    models.PositiveIntegerField(
                        help_text="Order within the round (0-based)."
                    ),
                ),
                (
                    "voting_open",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this match is currently accepting votes.",
                    ),
                ),
                (
                    "contestant_a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matches_as_a",
                        to="vore_day_rumble.contestant",
                    ),
                ),
                (
                    "contestant_b",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matches_as_b",
                        to="vore_day_rumble.contestant",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matches_won",
                        to="vore_day_rumble.contestant",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Matches",
                "ordering": ["round_number", "position"],
                "unique_together": {("round_number", "position")},
            },
        ),
    ]
