# Generated by Django 5.2.11 on 2026-08-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vore_day_rumble", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contestant",
            name="bracket_position",
            field=models.PositiveIntegerField(
                default=0, help_text="Slot in the bracket"
            ),
        ),
        migrations.AlterField(
            model_name="contestant",
            name="display_name",
            field=models.CharField(
                help_text="Name shown on the bracket (username or character name <3)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="position",
            field=models.PositiveIntegerField(help_text="Order in the round (0-based)"),
        ),
        migrations.AlterField(
            model_name="match",
            name="voting_open",
            field=models.BooleanField(
                default=False,
                help_text="Is this the match folks are voting on right now?",
            ),
        ),
        migrations.AlterField(
            model_name="rumblesettings",
            name="advance_to_next_match",
            field=models.BooleanField(
                default=False,
                help_text="Check + save to open the next match for voting. Clears itself after.",
            ),
        ),
        migrations.AlterField(
            model_name="rumblesettings",
            name="enabled",
            field=models.BooleanField(
                default=False, help_text="Master switch. Off = come back next year!"
            ),
        ),
        migrations.AlterField(
            model_name="rumblesettings",
            name="signups_open",
            field=models.BooleanField(
                default=False, help_text="Allow new contestants to sign up"
            ),
        ),
    ]
