# Generated by Django 5.2.11 on 2026-08-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vore_day_rumble", "0002_alter_contestant_bracket_position_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="discord_channel_id",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="match",
            name="discord_message_id",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="match",
            name="votes_left",
            field=models.PositiveIntegerField(
                blank=True, help_text="Final left-emoji tally (contestant A)", null=True
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="votes_right",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Final right-emoji tally (contestant B)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="voting_ends_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rumblesettings",
            name="discord_channel_id",
            field=models.CharField(
                blank=True,
                help_text="Discord channel ID where matchup votes get posted",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="rumblesettings",
            name="vote_duration_minutes",
            field=models.PositiveIntegerField(
                default=30, help_text="How long each Discord vote stays open"
            ),
        ),
    ]
