# Generated by Django 5.2.11 on 2026-08-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "vore_day_rumble",
            "0003_match_discord_channel_id_match_discord_message_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="rumblesettings",
            name="reset_bracket",
            field=models.BooleanField(
                default=False,
                help_text="Check + save to wipe winners/votes and reshuffle everyone. Clears itself after.",
            ),
        ),
    ]
