# Generated by Django 5.2.11 on 2026-08-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vore_day_rumble", "0004_rumblesettings_reset_bracket"),
    ]

    operations = [
        migrations.AddField(
            model_name="rumblesettings",
            name="champion_announced",
            field=models.BooleanField(
                default=False,
                help_text="Internal: already posted the WINNER card for this bracket.",
            ),
        ),
    ]
