# Generated by Django 5.2.11 on 2026-08-06 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vore_day_rumble", "0005_rumblesettings_champion_announced"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="votes_left",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Final tally for contestant A (set when vote closes)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="votes_right",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Final tally for contestant B (set when vote closes)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rumblesettings",
            name="discord_channel_id",
            field=models.CharField(
                blank=True,
                help_text="Discord channel ID for matchup announcements + results",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="rumblesettings",
            name="vote_duration_minutes",
            field=models.PositiveIntegerField(
                default=30, help_text="How long each site vote stays open"
            ),
        ),
        migrations.CreateModel(
            name="MatchVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice",
                    models.CharField(
                        choices=[("a", "Contestant A"), ("b", "Contestant B")],
                        max_length=1,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="vore_day_rumble.match",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vore_day_rumble_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("match", "user")},
            },
        ),
    ]
