# Generated by Django 5.1.6 on 2025-04-11 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("snowsune", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
