# Generated by Django 5.2.11 on 2026-05-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tanks_manager", "0004_tanksite_stage_fg_label_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tanksite",
            name="stage_fg_label_profile",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Cached [[y_pct_from_top, x_pct], …] from transparent scanlines; rebuilt on FG upload.",
            ),
        ),
    ]
