# Generated by Django 5.2.7 on 2025-11-03 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookclub", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprogress",
            options={"ordering": ["-page_number", "-updated_at"]},
        ),
        migrations.RemoveField(
            model_name="userprogress",
            name="position",
        ),
        migrations.AddField(
            model_name="monthlycomic",
            name="end_page",
            field=models.IntegerField(
                default=719, help_text="Ending page number (e.g., 719)"
            ),
        ),
        migrations.AddField(
            model_name="monthlycomic",
            name="start_page",
            field=models.IntegerField(
                default=0, help_text="Starting page number (e.g., 0)"
            ),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="page_number",
            field=models.IntegerField(default=0, help_text="Current page number"),
        ),
    ]
