# Generated by Django 5.2.7 on 2025-12-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookclub", "0002_alter_userprogress_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprogress",
            name="comment",
            field=models.TextField(
                blank=True, help_text="Optional comment about progress"
            ),
        ),
    ]
