# Generated by Django 5.2.7 on 2025-12-08 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookclub", "0003_userprogress_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlycomic",
            name="page_format_url",
            field=models.CharField(
                blank=True,
                help_text="URL format with {page_number} placeholder (e.g., https://example.com/page/{page_number})",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="monthlycomic",
            name="url",
            field=models.URLField(
                blank=True, help_text="Base URL for the comic (optional)", null=True
            ),
        ),
    ]
