# Generated by Django 5.2.7 on 2025-12-08 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookclub", "0005_comment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userprogress",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="comment",
            name="comic",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="bookclub.monthlycomic",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="monthlycomic",
            name="date_format",
            field=models.CharField(
                default="YYYYMMDD",
                help_text="Date format pattern (e.g., YYYYMMDD for 20251206). Use YYYY, MM, DD as placeholders.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="monthlycomic",
            name="use_date_format",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, parse page_number as a date using the date_format pattern",
            ),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="comic",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_progresses",
                to="bookclub.monthlycomic",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="userprogress",
            unique_together={("comic", "user")},
        ),
    ]
