# Generated by Django 5.1.6 on 2025-08-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ThankYou",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=100)),
                ("bio", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="thank_yous/"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order for manual sorting (0 = random)"
                    ),
                ),
                (
                    "social_links",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Social links as JSON: {"https://link.com": "Link Name"}',
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Thank You",
                "verbose_name_plural": "Thank Yous",
                "ordering": ["order", "name"],
            },
        ),
    ]
