# Generated by Django 5.1.6 on 2025-08-10 02:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="webhook_enabled",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="webhook_url",
        ),
    ]
