# Generated by Django 5.2.5 on 2025-10-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="discord_access_token",
            field=models.TextField(
                blank=True, null=True, verbose_name="Discord Access Token"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="discord_refresh_token",
            field=models.TextField(
                blank=True, null=True, verbose_name="Discord Refresh Token"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="discord_token_expires",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Discord Token Expires"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="discord_username",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Discord Username"
            ),
        ),
    ]
