# Generated by Django 5.2.5 on 2025-10-09 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_discord_access_token_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_moderator",
        ),
    ]
