# Generated by Django 5.1.6 on 2025-04-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_customuser_is_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="badges",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
