# Generated by Django 5.1.6 on 2025-07-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commorganizer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="draft",
            name="number",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
