# Generated by Django 5.1.6 on 2025-08-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commorganizer", "0004_commission_user_alter_commission_artist_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commission",
            name="name",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
