# Generated by Django 5.1.6 on 2025-06-15 17:54

from django.db import migrations
from django.utils.text import slugify


def create_initial_page(apps, schema_editor):
    EditablePage = apps.get_model("pages", "EditablePage")
    User = apps.get_model(
        "users", "CustomUser"
    )  # Assuming you have a custom user model

    # Get the first superuser to be the creator
    superuser = User.objects.filter(is_superuser=True).first()

    if not EditablePage.objects.filter(slug="hungerfight").exists():
        EditablePage.objects.create(
            title="Hunger Fight",
            slug="hungerfight",
            content="""# Hunger Fight

Welcome to the Hunger Fight page! This is where we'll document our efforts to fight hunger.

## What is Hunger Fight?

[Add description here]

## How Can You Help?

[Add ways to help here]

## Current Projects

[Add current projects here]

## Resources

[Add resources here]""",
            created_by=superuser,
            last_modified_by=superuser,
        )


def remove_initial_page(apps, schema_editor):
    EditablePage = apps.get_model("pages", "EditablePage")
    EditablePage.objects.filter(slug="hungerfight").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_initial_page, remove_initial_page),
    ]
