# Generated by Django 5.2.11 on 2026-08-19 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blog", "0003_comment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Poll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Markdown description shown with the poll.",
                    ),
                ),
                ("description_html", models.TextField(blank=True)),
                (
                    "flair",
                    models.CharField(
                        blank=True,
                        help_text="Short badge on the poll and blog preview (e.g. Community, Site, Comics).",
                        max_length=40,
                    ),
                ),
                (
                    "choice_type",
                    models.CharField(
                        choices=[
                            ("single", "Single choice"),
                            ("multi", "Multi choice"),
                        ],
                        default="single",
                        help_text="Single choice = pick one. Multi choice = pick several.",
                        max_length=10,
                    ),
                ),
                (
                    "max_choices",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="For multi choice: max options a voter can pick. 0 = no limit.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "opens_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional. If set, voting starts at this time.",
                        null=True,
                    ),
                ),
                (
                    "closes_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional. If set, voting ends at this time even if status is still Open.",
                        null=True,
                    ),
                ),
                (
                    "discord_votes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='After the poll closes, paste Discord vote counts keyed by choice id or label. Example: {"Pineapple": 14, "No pineapple": 31} or {"1": 14, "2": 31}',
                    ),
                ),
                (
                    "publish_to_blog",
                    models.BooleanField(
                        default=True,
                        help_text="Create/update a blog post when this poll is opened.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "blog_post",
                    models.OneToOneField(
                        blank=True,
                        help_text="Linked blog post so this poll shows up in the blog / homepage feed.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="poll",
                        to="blog.blogpost",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="polls_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="polls.poll",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "choice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="polls.choice",
                    ),
                ),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="polls.poll",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poll_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="poll",
            index=models.Index(
                fields=["status", "closes_at"], name="polls_poll_status_ce9694_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="poll",
            index=models.Index(fields=["slug"], name="polls_poll_slug_3e2bd9_idx"),
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(
                fields=["poll", "user"], name="polls_vote_poll_id_cfe401_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together={("poll", "user", "choice")},
        ),
    ]
